def titles
 [
  "Crow Valley Mansion",
  "Raindrop Residence",
  "Broadriver Residence",
  "Starfall Manor",
  "Tulipvale Chateau",
  "Soloning Mansion",
  "Fairder Estate",
  "Lanhope Residence",
  "Garretland Manor",
  "Rutherfield Chateau",
  "Myrtlewood Residence",
  "Belleview Manor",
  "Froglake Chateau",
  "Seaside Residence",
  "Hyacinth Manor",
  "Spenlace Estate",
  "Lamdal Mansion",
  "Wooryett Estate",
  "Rotsen Chateau",
  "Bridgedon Chateau",
  "Belcourt Estate",
  "Tanglewood Estate",
  "Ivywood Mansion",
  "Shadowplains Mansion",
  "Serenity Valley Residence",
  "Fieldaway Residence",
  "Nicksley Chateau",
  "Remdon Residence",
  "Consworth Manor",
  "Shearbot Manor",
  "Tulipvale Residence",
  "Peace Blossom Residence",
  "Sunrise Manor",
  "Noble Oak Manor",
  "Myrtlegrove Estate",
  "Foreler Chateau",
  "Rottker Estate",
  "Thornsend Estate",
  "Whitherd Mansion",
  "Padhold Chateau",
  "Jade River Estate",
  "Wild Willow Residence",
  "Froglake Residence",
  "Gentle Plains Manor",
  "Snowflake Manor",
  "Nickman Residence",
  "Harbrick Estate",
  "Humborne Mansion",
  "Goodters Mansion",
  "Conrow Estate",
  "Weeping Willow Mansion",
  "White Stag Mansion",
  "Ivywood Manor",
  "Crystal Hall Estate",
  "Davenmaker Chateau",
  "Maxcoll Chateau",
  "Esthall Manor",
  "Chalrance Chateau",
  "Spendrey Residence",
  "Spring Blossom Residence",
  "Clayriver Residence",
  "Pebblebrook Estate",
  "Newpoint Mansion",
  "Rutherkins Estate",
  "Browver Manor",
  "Clayding Manor",
  "Sweebard Manor",
  "Mernings Estate",
  "Belcourt Mansion",
  "Bayview Estate",
  "Restmeadow Mansion",
  "Noblebranch Manor",
  "Nickrish Residence",
  "Rothsger Manor",
  "Crawdaway Manor",
  "Conbarry Mansion",
  "Dristers Chateau",
  "Rosepetal Residence",
  "Morning Dew Residence",
  "Maplevale Chateau",
  "Lowvalley Mansion",
  "Walbrick Residence",
  "Hamilnelly Estate",
  "Blanston Residence",
  "Remdwell Residence",
  "Robinland Estate",
  "Oak Valley Estate",
  "Pebblebrook Chateau",
  "Boulderland Residence",
  "Beechwood Mansion",
  "Monttero Estate",
  "Wynner Chateau",
  "Covingwell Mansion",
  "Hennelly Residence",
  "Covingman Chateau",
  "Vanilla Bean Estate",
  "Sapphire Lake Estate",
  "Rosemary Chateau",
  "Castlemore Estate",
  "Drisnedy Residence",
  "Osbarth Mansion",
  "Conledge Residence",
  "Osmer Chateau",
  "Baldrey Estate",
  "Noble Oak Estate",
  "Seaside Chateau",
  "Cherry Grove Chateau",
  "Cedarworth Chateau",
  "Osay Residence",
  "Egerperd Manor",
  "Hendal Estate",
  "Stanvan Estate",
  "Estdaway Manor",
  "Ivylane Chateau",
  "Eagle's Nest Manor",
  "Woodrest Estate",
  "Cedarvale Mansion",
  "Shearmaker Residence",
  "Meacoll Residence",
  "Shurters Mansion",
  "Padrance Estate",
  "Arndell Estate",
  "Westwell Mansion",
  "Bridewater Mansion",
  "Starbrook Residence",
  "Lowvalley Estate",
  "Singomery Mansion",
  "Rutdon Mansion",
  "Osmond Manor",
  "Measey Residence",
  "Mortero Chateau",
  "Willow Vale Mansion",
  "Longford Manor",
  "Snowflake Residence",
  "Maplebrook Mansion",
  "Lanker Mansion",
  "Chaltero Manor",
  "Hamilson Mansion",
  "Weaney Chateau",
  "Stonewens Residence",
]
end
# spots = Spot.all
# idx = 0
# titles.each do |title|
#   spots[idx].title = title
#   spot.save
#   idx += 1
# end
